[package]
name = "bullet-hell"
version = "0.2.0"
authors = ["Mike <michaelpulliam1@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sdl2 = {version = "0.34", features = ["image", "ttf"]}
rand = "0.7"